#!/usr/bin/env python3
"""Richter: 2D FWI Result Viewer
Loads 2D FWI output files and renders velocity model comparison and misfit curve.

Expected files (generated by fwi_2d_demo):
  - fwi_2d_true.npy:     True velocity model
  - fwi_2d_initial.npy:  Initial guess
  - fwi_2d_velocity.npy: Final inverted velocity
  - fwi_2d_delta.npy:    Velocity change (inverted - initial)
  - fwi_2d_misfit.npy:   Misfit history (1D array)
"""

import numpy as np
import matplotlib.pyplot as plt
import sys
import os

def main():
    files = {
        'true': 'fwi_2d_true.npy',
        'initial': 'fwi_2d_initial.npy',
        'inverted': 'fwi_2d_velocity.npy',
        'delta': 'fwi_2d_delta.npy',
        'misfit': 'fwi_2d_misfit.npy',
    }

    for key, fname in files.items():
        if not os.path.exists(fname):
            print(f"Warning: {fname} not found. Run ./fwi_2d_demo first.")
            if key not in ('misfit', 'delta'):
                sys.exit(1)

    vel_true = np.load(files['true'])
    vel_init = np.load(files['initial'])
    vel_inv  = np.load(files['inverted'])

    has_delta = os.path.exists(files['delta'])
    vel_delta = np.load(files['delta']) if has_delta else vel_inv - vel_init

    has_misfit = os.path.exists(files['misfit'])
    misfit = np.load(files['misfit']) if has_misfit else None

    print(f"True:     shape={vel_true.shape}  range=[{vel_true.min():.0f}, {vel_true.max():.0f}] m/s")
    print(f"Initial:  shape={vel_init.shape}  range=[{vel_init.min():.0f}, {vel_init.max():.0f}] m/s")
    print(f"Inverted: shape={vel_inv.shape}   range=[{vel_inv.min():.0f}, {vel_inv.max():.0f}] m/s")

    nz, nx = vel_true.shape
    vel_error = vel_true - vel_inv

    # Global colorbar range
    vmin = min(vel_true.min(), vel_init.min(), vel_inv.min())
    vmax = max(vel_true.max(), vel_init.max(), vel_inv.max())

    fig, axes = plt.subplots(2, 3, figsize=(21, 10))

    # Row 1: True, Initial, Misfit curve
    im1 = axes[0, 0].imshow(vel_true, cmap='jet', aspect='auto',
                             vmin=vmin, vmax=vmax,
                             extent=[0, nx, nz, 0])
    axes[0, 0].set_title('True Velocity', fontsize=13, fontweight='bold')
    axes[0, 0].set_xlabel('X (grid points)')
    axes[0, 0].set_ylabel('Z / Depth (grid points)')
    plt.colorbar(im1, ax=axes[0, 0], label='m/s', shrink=0.8)

    im2 = axes[0, 1].imshow(vel_init, cmap='jet', aspect='auto',
                             vmin=vmin, vmax=vmax,
                             extent=[0, nx, nz, 0])
    axes[0, 1].set_title('Initial Guess', fontsize=13, fontweight='bold')
    axes[0, 1].set_xlabel('X (grid points)')
    axes[0, 1].set_ylabel('Z / Depth (grid points)')
    plt.colorbar(im2, ax=axes[0, 1], label='m/s', shrink=0.8)

    if has_misfit and misfit is not None and len(misfit) > 0:
        axes[0, 2].semilogy(np.arange(1, len(misfit) + 1), misfit, 'b-o', markersize=3)
        axes[0, 2].set_xlabel('Iteration')
        axes[0, 2].set_ylabel('L2 Misfit')
        axes[0, 2].set_title('Misfit Convergence', fontsize=13, fontweight='bold')
        axes[0, 2].grid(True, alpha=0.4)
    else:
        axes[0, 2].text(0.5, 0.5, 'No misfit data', ha='center', va='center',
                        transform=axes[0, 2].transAxes)

    # Row 2: Inverted, Error, Depth profile
    im3 = axes[1, 0].imshow(vel_inv, cmap='jet', aspect='auto',
                             vmin=vmin, vmax=vmax,
                             extent=[0, nx, nz, 0])
    axes[1, 0].set_title('Inverted Velocity', fontsize=13, fontweight='bold')
    axes[1, 0].set_xlabel('X (grid points)')
    axes[1, 0].set_ylabel('Z / Depth (grid points)')
    plt.colorbar(im3, ax=axes[1, 0], label='m/s', shrink=0.8)

    err_max = np.percentile(np.abs(vel_error), 99)
    if err_max == 0: err_max = 1.0
    im4 = axes[1, 1].imshow(vel_error, cmap='seismic', aspect='auto',
                             vmin=-err_max, vmax=err_max,
                             extent=[0, nx, nz, 0])
    axes[1, 1].set_title('Velocity Error (True - Inverted)', fontsize=13, fontweight='bold')
    axes[1, 1].set_xlabel('X (grid points)')
    axes[1, 1].set_ylabel('Z / Depth (grid points)')
    plt.colorbar(im4, ax=axes[1, 1], label='m/s', shrink=0.8)

    # 1D depth profile comparison (center column)
    x_mid = nx // 2
    z_axis = np.arange(nz)
    axes[1, 2].plot(vel_true[:, x_mid], z_axis, 'k-', linewidth=2, label='True')
    axes[1, 2].plot(vel_init[:, x_mid], z_axis, 'b--', linewidth=1.5, label='Initial')
    axes[1, 2].plot(vel_inv[:, x_mid], z_axis, 'r-', linewidth=2, label='Inverted')
    axes[1, 2].set_ylim(nz, 0)
    axes[1, 2].set_xlabel('Velocity (m/s)')
    axes[1, 2].set_ylabel('Z / Depth (grid points)')
    axes[1, 2].set_title('1D Depth Profile (x=center)', fontsize=13, fontweight='bold')
    axes[1, 2].legend(loc='best')
    axes[1, 2].grid(True, alpha=0.4)

    fig.suptitle('2D FWI Result', fontsize=15, fontweight='bold', y=1.01)
    plt.tight_layout()
    plt.savefig('fwi_2d_result.png', dpi=150, bbox_inches='tight')
    print("Saved fwi_2d_result.png")
    plt.show()

if __name__ == '__main__':
    main()
